Intial commit: ui
BURG3R5/mdg-chat-frontend pull request #2
Opened 2021-05-17 19:42 UTC by aman-singh7

2021-05-18 14:05 UTC, BURG3R5 requested changes
Made some suggestions. Check them out when you have the time. When you can, make some changes and commit them. I'll approve the PR after that.

2021-05-18 14:05 UTC, BURG3R5 commented on lib/models/chat.dart
> +  final String name, lastMessage, image, time;
The properties and functions of this model can be disolved into the Message model and viewmodel and the User model and viewmodel. I'll handle that in the next commit on my branch.

2021-05-18 16:03 UTC, aman-singh7 commented on lib/ui/components/filled_outline_button.dart
> +    Key key,
Yeah, it is auto-generated in vs code.

2021-05-18 16:06 UTC, aman-singh7 commented on lib/models/chat.dart
> +    name: "Aditye Rajput",
Are sorry for the typo.😅

2021-05-18 16:06 UTC, aman-singh7 commented on lib/ui/views/chats/chats_screen.dart
> +      body: Body(),
I have extracted it to make the code more readable.

2021-05-18 16:09 UTC, aman-singh7 commented on lib/models/chat.dart
> +  final String name, lastMessage, image, time;
It will be handled in the view model when we retrieve data from database. Right now I have hard coded in the same file.

2021-05-18 16:13 UTC, aman-singh7 commented on lib/main.dart
> +import 'package:mdg_chat/ui/views/opening_screen.dart';
No, It is not possible because vs code auto format my code on saving. So, these spaces can not be resolved.😅

2021-05-20 03:42 UTC, BURG3R5 commented on lib/ui/views/chats/body.dart
> +import './chat_card.dart';
Man _I_ use `import 'chat_card.dart';` I'll merge this, and make the change afterwards.

2021-05-20 03:47 UTC, BURG3R5 approved these changes
Awesome!

2021-05-20 03:48 UTC, merged

2021-05-20 03:50 UTC, BURG3R5 commented
Continue working on this same branch. We'll follow this same pattern of work-commit-PR-review-merge. 👍🏻